<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{
    public function byCategorie($category)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.category = :category')
            ->andWhere('u.disponible = 1')
            ->orderBy('u.id')
            ->setParameter('category', $category);
        return $qb->getQuery()->getResult();
    }

    public function recherche($chaine)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.nom like :chaine')
            ->andWhere('u.disponible = 1')
            ->orderBy('u.id')
            ->setParameter('chaine', $chaine);
        return $qb->getQuery()->getResult();
    }

    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.id IN (:array)')
            ->setParameter(':array', $array);
        return $qb->getQuery()->getResult();
    }
}
