front_produit:
    resource: "@AppBundle/Resources/config/routing/front-office/produit.yml"

front_livraison:
    resource: "@AppBundle/Resources/config/routing/front-office/livraison.yml"

front_panier:
    resource: "@AppBundle/Resources/config/routing/front-office/panier.yml"


front_category:
    resource: "@AppBundle/Resources/config/routing/front-office/category.yml"

front_test:
    resource: "@AppBundle/Resources/config/routing/front-office/test.yml"
