categories_index:
    path:     /
    defaults: { _controller: "AppBundle:BackOffice/Category:index" }
    methods:  GET

category_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Categories:show" }
    methods:  GET

category_new:
    path:     /new
    defaults: { _controller: "AppBundle:BackOffice/Category:new" }
    methods:  [GET, POST]

categories_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Categories:edit" }
    methods:  [GET, POST]

categories_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Categories:delete" }
    methods:  DELETE
