utilisateurs_index:
    path:     /
    defaults: { _controller: "AppBundle:Utilisateurs:index" }
    methods:  GET

utilisateurs_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Utilisateurs:show" }
    methods:  GET

utilisateurs_new:
    path:     /new
    defaults: { _controller: "AppBundle:Utilisateurs:new" }
    methods:  [GET, POST]

utilisateurs_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Utilisateurs:edit" }
    methods:  [GET, POST]

utilisateurs_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Utilisateurs:delete" }
    methods:  DELETE
