services:
    tva:
      class: AppBundle\Twig\Extension\TvaExtension
      tags:
        - { name: twig.extension }
    montantTva:
      class: AppBundle\Twig\Extension\montantTvaExtension
      tags:
        - { name: twig.extension }

    redirectionListener:
      class: AppBundle\Listener\RedirectionListener
      arguments: [@service_container, @session]
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest}
