front_produits_produit:
    path:     /liste-produits
    defaults: { _controller: "AppBundle:FrontOffice/ProduitsFront:produit" }
    methods:  GET

front_produits_recherche_traitement:
    path:     /rechercheTraitementProduits
    defaults: { _controller: "AppBundle:FrontOffice/PropertyFront:rechercheTraitement" }
    methods:  GET

front_produits_recherche:
    path:     /rehercheproduits
    defaults: { _controller: "AppBundle:FrontOffice/PropertyFront:recherche" }

front_produits_search:
    path:     /presentation-produits
    defaults: { _controller: "AppBundle:FrontOffice/PropertyFront:presentationProduits" }
    methods:  GET

front_produits_form_search:
    path:     /display-form
    defaults: { _controller: "AppBundle:FrontOffice/PropertyFront:formSearch" }